### ISSUE TITLE
large researchTime value makes labs unusable

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/BetterScienceLabsContinued#6]
Some of the labs have large researchTime values. 
The field is exponential, so the `researchTime = 13` makes labs 1000000 times slower.
There is `dataProcessingMultiplier` for a linear managing research speed

**Comment by linuxgurugamer** [comment]
I'm open to suggestions

**Comment by yalov** [comment]
I am not using the mod, but noticed the values when was making and testing [Science Lab Info](https://forum.kerbalspaceprogram.com/index.php?/topic/179385-151-science-lab-info-and-6-crew-lab/)

**Comment by linuxgurugamer** [comment]
Ok, I'm going to reduce most of those to 8, hopefully that won't make them too good.

Thanks
