### ISSUE TITLE
Missing textures - Conflict with Restock

### ISSUE THREAD

**Issue by SmallerDragons** [linuxgurugamer/BetterScienceLabsContinued#8]
Mobile Processing labs are missing textures when mod ReStock (v1.4.1) is installed.
This issue can be recreated by simply installing ReStock+ (latest) while Better Science Labs (v0.2.0) is installed.
![Missing Texture](https://user-images.githubusercontent.com/88168639/127579013-d7b75594-5e6a-4922-b7b0-1f6813505e79.png)

**Comment by linuxgurugamer** [comment]
Please post in the thread, where others can help as well
